import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router";
import { ChevronLeft, Sparkles, ChefHat } from "lucide-react";
import { useIngredients } from "../services/IngredientContext";
import { llmService } from "../services/llmService";
import { getRecommendedRecipes } from "../data/recipes";
import { RecipeCard } from "../components/recipes/RecipeCard";
import { IngredientCloud } from "../components/recipes/IngredientCloud";

export function Recipes() {
    const navigate = useNavigate();
    const { scannedItems, recommendedRecipes, setRecipes, t } = useIngredients();
    const [hasAttempted, setHasAttempted] = useState(false);
    const [isLoading, setIsLoading] = useState(true);

    useEffect(() => {
        if (scannedItems.length > 0 && recommendedRecipes.length === 0 && !hasAttempted) {
            const fetchRecipes = async () => {
                setIsLoading(true);
                setHasAttempted(true);
                try {
                    const res = await llmService.generateRecipes({ 
                        ingredients: scannedItems.map(i => i.name),
                        onOptimisticResult: (optimisticRecipes) => {
                            setRecipes(optimisticRecipes);
                            setIsLoading(false); 
                        }
                    });
                    setRecipes(res);
                } catch (error) {
                    setRecipes(getRecommendedRecipes(scannedItems));
                } finally {
                    setIsLoading(false);
                }
            };
            fetchRecipes();
        } else if (recommendedRecipes.length > 0 || scannedItems.length === 0 || hasAttempted) {
            setIsLoading(false);
        }
    }, [scannedItems, recommendedRecipes, setRecipes, hasAttempted]);

    return (
        <div className="pb-28 pt-6 relative">
            {/* Minimal Floating Back Button */}
            <button
                onClick={() => navigate(-1)}
                className="fixed top-4 left-4 z-[110] w-10 h-10 bg-card border-4 border-white flex items-center justify-center shadow-[4px_4px_0px_0px_rgba(0,0,0,0.5)] active:translate-x-[2px] active:translate-y-[2px] active:shadow-none transition-all text-white"
            >
                <ChevronLeft size={20} />
            </button>

            <div className="px-6 py-4">
                <div className="flex items-center gap-4 mb-8">
                    <div className="p-3 bg-primary/10 border-4 border-primary shadow-[4px_4px_0px_0px_rgba(0,0,0,0.5)]">
                        <Sparkles size={24} className="text-primary" />
                    </div>
                    <div>
                        <h1 className="text-primary arcade-glow text-xl font-black mb-1 leading-none tracking-widest">PROPOSALS</h1>
                        <p className="text-[8px] text-primary/60 font-black uppercase tracking-[0.2em]">GENERATED BY AI NODE 03</p>
                    </div>
                </div>

                <IngredientCloud items={scannedItems} onAddMore={() => navigate("/inventory")} />

                {isLoading ? (
                    <div className="space-y-6">
                        {/* Status Panel */}
                        <div className="flex flex-col gap-2.5 items-center justify-center py-8 bg-white/5 border-4 border-primary/20 shadow-[8px_8px_0px_0px_rgba(0,0,0,0.3)]">
                            <h3 className="text-primary font-black text-[10px] uppercase animate-pulse mb-3 tracking-[0.2em]">{t('recipes.analyzing')}</h3>
                            <div className="flex flex-col gap-3 items-start">
                                <LoadingStep icon="🤖" label={t('recipes.synthesizing')} delay="0s" />
                                <LoadingStep icon="📋" label={t('recipes.filtering')} delay="0.5s" />
                                <LoadingStep icon="✅" label={t('recipes.verification')} delay="1s" />
                            </div>
                        </div>

                        {/* Skeleton Grid */}
                        <div className="grid grid-cols-2 gap-4 opacity-40">
                            {[...Array(4)].map((_, i) => (
                                <RecipeSkeleton key={i} />
                            ))}
                        </div>
                    </div>
                ) : recommendedRecipes.length > 0 ? (
                    <div className="space-y-4 optimize-list">
                        {/* Safety Banner */}
                        <div className="flex items-center gap-3 px-4 py-3 bg-primary/10 border-4 border-primary/20">
                            <span className="text-base">✅</span>
                            <p className="text-primary text-[8px] font-black uppercase tracking-widest">
                                {t('recipes.complete')}
                            </p>
                        </div>
                        <div className="grid grid-cols-2 gap-4">
                            {recommendedRecipes.map((r) => (
                                <RecipeCard
                                    key={r.id}
                                    recipe={r}
                                    onClick={() => navigate(`/recipe/${r.id}`)}
                                />
                            ))}
                        </div>
                    </div>
                ) : (
                    <div className="text-center py-20 px-6 bg-white/5 border-4 border-dashed border-white/10">
                        <div className="w-16 h-16 mx-auto mb-6 bg-primary/10 border-4 border-primary/20 flex items-center justify-center shadow-[6px_6px_0px_0px_rgba(0,0,0,0.2)]">
                            <ChefHat size={32} className="text-primary/30" />
                        </div>
                        <h4 className="text-white font-black text-xs uppercase mb-6 tracking-widest leading-loose">{t('recipes.no_protocols')}<br/>{t('recipes.rescan')}</h4>
                        <button
                            onClick={() => navigate("/")}
                            className="inline-flex items-center gap-2 px-8 py-4 bg-primary text-background border-4 border-black font-black uppercase text-[10px] tracking-widest shadow-[6px_6px_0px_0px_rgba(0,0,0,0.4)] active:translate-x-[3px] active:translate-y-[3px] active:shadow-none transition-all"
                        >
                            {t('recipes.return')}
                        </button>
                    </div>
                )}
            </div>
        </div>
    );
}

/** Pixel Skeleton Component */
function RecipeSkeleton() {
    return (
        <div className="bg-white/5 border-4 border-white/5 p-2 flex flex-col gap-3 h-full shadow-[4px_4px_0px_0px_rgba(0,0,0,0.2)]">
            <div className="relative w-full aspect-square bg-white/5 border-2 border-white/10 overflow-hidden">
                <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/5 to-transparent -translate-x-full animate-[shimmer_2s_infinite]" />
            </div>
            <div className="space-y-2 px-1 pb-2">
                <div className="h-2 w-1/2 bg-white/10" />
                <div className="h-3 w-full bg-white/10" />
                <div className="h-8 w-full bg-white/5 border-2 border-white/10 mt-2" />
            </div>
        </div>
    );
}

/** Loading Step with Pixel Animation */
function LoadingStep({ icon, label, delay }: { icon: string; label: string; delay: string }) {
    return (
        <div
            className="flex items-center gap-3 opacity-0 pixel-fade-in"
            style={{ animationDelay: delay }}
        >
            <span className="text-[10px]">{icon}</span>
            <span className="text-white/50 text-[7px] font-bold uppercase tracking-[0.2em]">{label}</span>
        </div>
    );
}
